'use client';

import InfiniteLoadingEffect from "@/components/loading/infinite";
import { Metadata } from "next"

export const metadata: Metadata = {
	title: 'DeveTools - Find facebook account',
	description: 'Generated by create next app',
}

export default function Page() {
	return (
		<>
			<h1>Find facebook</h1>
		</>
	)
}